---
###
### ttt
###
- name: develop | debian | ttt
  pip:
    name: 'git+{{ ttt_repository }}'
    editable: false
    state: present

- name: develop | MAKEFLAGS
  become: yes
  become_user: vagrant
  lineinfile:
    path: ~/.bashrc
    regexp: '^export MAKEFLAGS=-j3'
    line: 'export MAKEFLAGS=-j3'

- name: develop | MESA_GL_VERSION_OVERRIDE
  become: yes
  become_user: vagrant
  lineinfile:
    path: ~/.bashrc
    regexp: '^export MESA_GL_VERSION_OVERRIDE=4.3'
    line: 'export MESA_GL_VERSION_OVERRIDE=4.3'

- name: develop | MESA_GLSL_VERSION_OVERRIDE
  become: yes
  become_user: vagrant
  lineinfile:
    path: ~/.bashrc
    regexp: '^export MESA_GLSL_VERSION_OVERRIDE=430'
    line: 'export MESA_GLSL_VERSION_OVERRIDE=430'

