---
###
### ttt
###

- name: develop | windows | Install ttt
  win_shell: "pip install git+{{ ttt_repository }}"

##
## Make developing on Windows tolerable
##
- name: windows | Get classic shell
  win_get_url:
    url: http://www.mediafire.com/download/dbbil746gavpirr/ClassicShellSetup_4_3_0.exe
    dest: "{{ download_location }}\\ClassicShellSetup_4_3_0.exe"

- name: classic shell | Install
  win_package:
    name: Classic Shell
    path: "{{ download_location }}\\ClassicShellSetup_4_3_0.exe"
    product_id: "{383BB30A-B4A7-4666-9A83-22CFA8640097}"
    arguments: "/qn ADDLOCAL=ClassicStartMenu"

- name: Remove classic shell installer
  win_file:
    path: "{{ download_location }}\\ClassicShellSetup_4_3_0.exe"
    state: absent

# Debloat Windows

- name: Checking common setup
  win_stat:
    path: .debloated
  register: debloated

- name: windows | Download debloat tool
  win_get_url:
    url: https://github.com/W4RH4WK/Debloat-Windows-10/archive/master.zip
    dest: "{{ download_location }}\\Debloat-Windows-10-master.zip"
  when: not debloated.stat.exists

- name: Extract debloater
  win_unzip:
    src: "{{ download_location }}\\Debloat-Windows-10-master.zip"
    dest: "{{ download_location }}"
    creates: "{{ download_location }}\\scripts"
  when: not debloated.stat.exists

- name: Execute debloat scripts; part 1
  win_shell: "{{ download_location }}/Debloat-Windows-10-master/scripts/disable-windows-defender.ps1"
  when: not debloated.stat.exists

- name: restart machine
  win_reboot:
  when: not debloated.stat.exists

- name: windows | wait for vagrant mount
  win_stat:
      path: "c:\\tmp\\vagrant-cache"
  register: mount
  until: mount.stat.exists
  retries: 10
  delay: 6

- name: Execute debloat scripts; part 2
  win_shell: "{{ download_location }}/Debloat-Windows-10-master/scripts/{{ item }}"
  with_items:
    - disable-windows-defender.ps1
    - block-telemetry.ps1
    - disable-services.ps1
    - fix-privacy-settings.ps1
    - optimize-user-interface.ps1
    - optimize-windows-update.ps1
    - remove-default-apps.ps1
    - remove-onedrive.ps1
  when: not debloated.stat.exists

- name: restart machine
  win_reboot:
  when: not debloated.stat.exists

- name: windows | wait for vagrant mount
  win_stat:
      path: "c:\\tmp\\vagrant-cache"
  register: mount
  until: mount.stat.exists
  retries: 10
  delay: 6

- name: Remove debloat utilities
  win_file:
    path: "{{ download_location }}\\{{ item }}"
    state: absent
  with_items:
    - Debloat-Windows-10-master.zip
    - Debloat-Windows-10-master
  when: not debloated.stat.exists

- name: Removal complete
  win_file:
    name: .debloated
    state: touch
  when: not debloated.stat.exists

