---
- name: restart ircd
  service:
    name: inspircd
    state: restarted

- name: restart buildbot
  service:
    name: buildmaster
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted

