---
- name: Wait for SSH
  local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH

#
# HOSTS
#
- name: Add servers to unix /etc/hosts
  template:
    dest: "{{ etc_hosts_file }}"
    src: hosts.Debian.j2
  when: ansible_hostname in groups['unix']
  tags: [common,hosts]

##
## APT
##
- name: Set up mirror
  template:
    src: etc_apt_sources.list.{{ ansible_distribution }}.j2
    dest: /etc/apt/sources.list
    backup: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - apt-transport-https
    - sudo
    - vim
    - git
    - ntp

- name: Upgrade all safe packages
  apt:
    upgrade: safe

- name: Install unattended upgrades
  apt:
    pkg: unattended-upgrades
    state: present

##
## NTP
##
- name: Configure ntp
  template:
    src: ntp.conf.Debian.j2
    dest: /etc/ntp.conf
  notify: restart ntp

##
## SECURITY
##
# # This task can be used for OSX only if notification works.
# - name: Update sshd config to disallow root logins
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     regexp: ^PermitRootLogin
#     line: "PermitRootLogin no"
#     state: present
#   notify: restart ssh

