---
##
## CLONE
##
- name: master | Add github to known_hosts
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- include: ircd.yml
  tags: ircd
- include: nginx.yml
  tags: nginx
- include: buildmaster.yml
  tags: buildbot

# Force handlers so the web sites are accessible
- meta: flush_handlers

