---
##
## APT DEPENDENCIES
##
- name: nginx | Install nginx
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx

##
## NGINX
##
- name: nginx | Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Change www location owner
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    mode: 0775

