---
- include: windows_cache_download.yml

- name: git | Installed?
  win_stat:
    path: "C:\\Program Files\\Git"
  register: app

- name: git | Install
  raw: "{{ download_location }}\\{{ file }} /SILENT"
  when: not app.stat.exists

- name: git | Add to path
  raw: powershell [System.Environment]::SetEnvironmentVariable('Path',$Env:Path+';C:\Program Files\Git\bin','Machine')
  when: not app.stat.exists

- include: windows_clean.yml

