---
###
### Mesa llvmpipe OpenGL software renderer
### https://github.com/pal1000/mesa-dist-win/releases
### Windows on virtualbox is limited to 2.1 at best.
###

- name: opengl | MESA Installed?
  win_stat:
    path: C:\mesa
  register: mesa

- name: opengl | Install MESA
  win_shell: cmd /c "{{ download_location }}\\{{ mesa_file }} -oc:\\mesa -y"
  when: not mesa.stat.exists

- name: opengl | Set MESA environment variable
  win_environment:
    name: MESA
    value: c:\mesa\x86
    state: present
    level: user
  when: not mesa.stat.exists

- name: opengl | Set MESA environment variable GL override
  win_environment:
    name: MESA_GL_VERSION_OVERRIDE
    value: 4.3
    state: present
    level: user
  when: not mesa.stat.exists

- name: opengl | Set MESA environment variable GL override
  win_environment:
    name: MESA_GLSL_VERSION_OVERRIDE
    value: 430
    state: present
    level: user
  when: not mesa.stat.exists

